# Generated by Django 2.2.12 on 2022-06-09 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='static/site-data/profile-pictures')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('verification_code', models.CharField(default='no', max_length=5)),
                ('blocked_status', models.BooleanField(default=False)),
                ('tenant_status', models.BooleanField(default=False)),
                ('landlord_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Cancelled')], default=1, max_length=18)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.appUser')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('location', models.TextField()),
                ('facilities', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('photos', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.appUser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to='app.appUser')),
            ],
        ),
    ]
