# Generated by Django 2.2.12 on 2022-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220610_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room_request',
            name='room_id',
            field=models.IntegerField(default=None),
        ),
    ]
