# Generated by Django 2.2.12 on 2022-06-10 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220610_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_request',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
